# Generated by Django 4.1.3 on 2022-11-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataPoints',
            new_name='Datapoint',
        ),
    ]
